# Generated by Django 5.2.1 on 2025-05-30 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
